version: '2'
services:
  top_sort:
    image: hadyelzayady1996/light-app-topological-sort:latest
    networks:
      - queue-service

  # lredis:
  #   build: ../redis-light
  #   ports:
  #     - 50051:50051
  # fib_calc:
  #   depends_on:
  #     - sqs
  #     - lredis
  #   build: ./backend/fib-calc
  #   ports:
  #     - 8001:8001
  frontend:
    image: hadyelzayady1996/light-app-frontend
  reverse-proxy:
    image: hadyelzayady1996/light-app-frontend

networks:
  queue-service:
    name: queue-service
    external: true
